# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Provider.create(name: "Indeed", base_show_url: "https://uk.indeed.com/viewjob?jk=")
Provider.create(name: "LinkedIn", base_show_url: "https://www.linkedin.com/jobs/view/")
Provider.create(name: "Reed", base_show_url: "https://www.reed.co.uk/jobs/")

Country.create(name: "Argentina")
Country.create(name: "Australia")
Country.create(name: "Austria")
Country.create(name: "Bahrain")
Country.create(name: "Belgium")
Country.create(name: "Brazil")
Country.create(name: "Canada")
Country.create(name: "Chile")
Country.create(name: "China")
Country.create(name: "Colombia")
Country.create(name: "Costa Rica")
Country.create(name: "Czech Republic")
Country.create(name: "Denmark")
Country.create(name: "Ecuador")
Country.create(name: "Egypt")
Country.create(name: "Finland")
Country.create(name: "France")
Country.create(name: "Germany")
Country.create(name: "Greece")
Country.create(name: "Hong Kong")
Country.create(name: "Hungary")
Country.create(name: "India")
Country.create(name: "Indonesia")
Country.create(name: "Ireland")
Country.create(name: "Israel")
Country.create(name: "Italy")
Country.create(name: "Japan")
Country.create(name: "Kuwait")
Country.create(name: "Luxembourg")
Country.create(name: "Malaysia")
Country.create(name: "Mexico")
Country.create(name: "Morocco")
Country.create(name: "Netherlands")
Country.create(name: "New Zealand")
Country.create(name: "Nigeria")
Country.create(name: "Norway")
Country.create(name: "Oman")
Country.create(name: "Pakistan")
Country.create(name: "Panama")
Country.create(name: "Peru")
Country.create(name: "Philippines")
Country.create(name: "Poland")
Country.create(name: "Portugal")
Country.create(name: "Qatar")
Country.create(name: "Romania")
Country.create(name: "Russia")
Country.create(name: "Saudi Arabia")
Country.create(name: "Singapore")
Country.create(name: "South Africa")
Country.create(name: "South Korea")
Country.create(name: "Spain")
Country.create(name: "Sweden")
Country.create(name: "Switzerland")
Country.create(name: "Taiwan")
Country.create(name: "Thailand")
Country.create(name: "Turkey")
Country.create(name: "Ukraine")
Country.create(name: "United Arab Emirates")
Country.create(name: "United Kingdom")
Country.create(name: "United States")
Country.create(name: "Uruguay")
Country.create(name: "Venezuela")
Country.create(name: "Vietnam")

ProviderCountry.create(provider_id: 1, country_id: 1, code: "ar")
ProviderCountry.create(provider_id: 1, country_id: 2, code: "au")
ProviderCountry.create(provider_id: 1, country_id: 3, code: "at")
ProviderCountry.create(provider_id: 1, country_id: 4, code: "bh")
ProviderCountry.create(provider_id: 1, country_id: 5, code: "be")
ProviderCountry.create(provider_id: 1, country_id: 6, code: "br")
ProviderCountry.create(provider_id: 1, country_id: 7, code: "ca")
ProviderCountry.create(provider_id: 1, country_id: 8, code: "cl")
ProviderCountry.create(provider_id: 1, country_id: 9, code: "cn")
ProviderCountry.create(provider_id: 1, country_id: 10, code: "co")
ProviderCountry.create(provider_id: 1, country_id: 11, code: "cr")
ProviderCountry.create(provider_id: 1, country_id: 12, code: "cz")
ProviderCountry.create(provider_id: 1, country_id: 13, code: "dk")
ProviderCountry.create(provider_id: 1, country_id: 14, code: "ec")
ProviderCountry.create(provider_id: 1, country_id: 15, code: "eg")
ProviderCountry.create(provider_id: 1, country_id: 16, code: "fi")
ProviderCountry.create(provider_id: 1, country_id: 17, code: "fr")
ProviderCountry.create(provider_id: 1, country_id: 18, code: "de")
ProviderCountry.create(provider_id: 1, country_id: 19, code: "gr")
ProviderCountry.create(provider_id: 1, country_id: 20, code: "hk")
ProviderCountry.create(provider_id: 1, country_id: 21, code: "hu")
ProviderCountry.create(provider_id: 1, country_id: 22, code: "in")
ProviderCountry.create(provider_id: 1, country_id: 23, code: "id")
ProviderCountry.create(provider_id: 1, country_id: 24, code: "ie")
ProviderCountry.create(provider_id: 1, country_id: 25, code: "il")
ProviderCountry.create(provider_id: 1, country_id: 26, code: "it")
ProviderCountry.create(provider_id: 1, country_id: 27, code: "jp")
ProviderCountry.create(provider_id: 1, country_id: 28, code: "kw")
ProviderCountry.create(provider_id: 1, country_id: 29, code: "lu")
ProviderCountry.create(provider_id: 1, country_id: 30, code: "malaysia")
ProviderCountry.create(provider_id: 1, country_id: 31, code: "mx")
ProviderCountry.create(provider_id: 1, country_id: 32, code: "ma")
ProviderCountry.create(provider_id: 1, country_id: 33, code: "nl")
ProviderCountry.create(provider_id: 1, country_id: 34, code: "nz")
ProviderCountry.create(provider_id: 1, country_id: 35, code: "ng")
ProviderCountry.create(provider_id: 1, country_id: 36, code: "no")
ProviderCountry.create(provider_id: 1, country_id: 37, code: "om")
ProviderCountry.create(provider_id: 1, country_id: 38, code: "pk")
ProviderCountry.create(provider_id: 1, country_id: 39, code: "pa")
ProviderCountry.create(provider_id: 1, country_id: 40, code: "pe")
ProviderCountry.create(provider_id: 1, country_id: 41, code: "ph")
ProviderCountry.create(provider_id: 1, country_id: 42, code: "pl")
ProviderCountry.create(provider_id: 1, country_id: 43, code: "pt")
ProviderCountry.create(provider_id: 1, country_id: 44, code: "qa")
ProviderCountry.create(provider_id: 1, country_id: 45, code: "ro")
ProviderCountry.create(provider_id: 1, country_id: 46, code: "ru")
ProviderCountry.create(provider_id: 1, country_id: 47, code: "sa")
ProviderCountry.create(provider_id: 1, country_id: 48, code: "sg")
ProviderCountry.create(provider_id: 1, country_id: 49, code: "za")
ProviderCountry.create(provider_id: 1, country_id: 50, code: "kr")
ProviderCountry.create(provider_id: 1, country_id: 51, code: "es")
ProviderCountry.create(provider_id: 1, country_id: 52, code: "se")
ProviderCountry.create(provider_id: 1, country_id: 53, code: "ch")
ProviderCountry.create(provider_id: 1, country_id: 54, code: "tw")
ProviderCountry.create(provider_id: 1, country_id: 55, code: "th")
ProviderCountry.create(provider_id: 1, country_id: 56, code: "tr")
ProviderCountry.create(provider_id: 1, country_id: 57, code: "ua")
ProviderCountry.create(provider_id: 1, country_id: 58, code: "ae")
ProviderCountry.create(provider_id: 1, country_id: 59, code: "uk")
ProviderCountry.create(provider_id: 1, country_id: 60, code: "")
ProviderCountry.create(provider_id: 1, country_id: 61, code: "uy")
ProviderCountry.create(provider_id: 1, country_id: 62, code: "ve")
ProviderCountry.create(provider_id: 1, country_id: 63, code: "vn")