class CreateProviderCountries < ActiveRecord::Migration[5.2]
  def change
    create_table :provider_countries do |t|
      t.integer :provider_id
      t.integer :country_id
      t.string :code

      t.timestamps
    end

    ProviderCountry.create(provider_id: 1, country_id: 1, code: "ar")
    ProviderCountry.create(provider_id: 1, country_id: 2, code: "au")
    ProviderCountry.create(provider_id: 1, country_id: 3, code: "at")
    ProviderCountry.create(provider_id: 1, country_id: 4, code: "bh")
    ProviderCountry.create(provider_id: 1, country_id: 5, code: "be")
    ProviderCountry.create(provider_id: 1, country_id: 6, code: "br")
    ProviderCountry.create(provider_id: 1, country_id: 7, code: "ca")
    ProviderCountry.create(provider_id: 1, country_id: 8, code: "cl")
    ProviderCountry.create(provider_id: 1, country_id: 9, code: "cn")
    ProviderCountry.create(provider_id: 1, country_id: 10, code: "co")
    ProviderCountry.create(provider_id: 1, country_id: 11, code: "cr")
    ProviderCountry.create(provider_id: 1, country_id: 12, code: "cz")
    ProviderCountry.create(provider_id: 1, country_id: 13, code: "dk")
    ProviderCountry.create(provider_id: 1, country_id: 14, code: "ec")
    ProviderCountry.create(provider_id: 1, country_id: 15, code: "eg")
    ProviderCountry.create(provider_id: 1, country_id: 16, code: "fi")
    ProviderCountry.create(provider_id: 1, country_id: 17, code: "fr")
    ProviderCountry.create(provider_id: 1, country_id: 18, code: "de")
    ProviderCountry.create(provider_id: 1, country_id: 19, code: "gr")
    ProviderCountry.create(provider_id: 1, country_id: 20, code: "hk")
    ProviderCountry.create(provider_id: 1, country_id: 21, code: "hu")
    ProviderCountry.create(provider_id: 1, country_id: 22, code: "in")
    ProviderCountry.create(provider_id: 1, country_id: 23, code: "id")
    ProviderCountry.create(provider_id: 1, country_id: 24, code: "ie")
    ProviderCountry.create(provider_id: 1, country_id: 25, code: "il")
    ProviderCountry.create(provider_id: 1, country_id: 26, code: "it")
    ProviderCountry.create(provider_id: 1, country_id: 27, code: "jp")
    ProviderCountry.create(provider_id: 1, country_id: 28, code: "kw")
    ProviderCountry.create(provider_id: 1, country_id: 29, code: "lu")
    ProviderCountry.create(provider_id: 1, country_id: 30, code: "malaysia")
    ProviderCountry.create(provider_id: 1, country_id: 31, code: "mx")
    ProviderCountry.create(provider_id: 1, country_id: 32, code: "ma")
    ProviderCountry.create(provider_id: 1, country_id: 33, code: "nl")
    ProviderCountry.create(provider_id: 1, country_id: 34, code: "nz")
    ProviderCountry.create(provider_id: 1, country_id: 35, code: "ng")
    ProviderCountry.create(provider_id: 1, country_id: 36, code: "no")
    ProviderCountry.create(provider_id: 1, country_id: 37, code: "om")
    ProviderCountry.create(provider_id: 1, country_id: 38, code: "pk")
    ProviderCountry.create(provider_id: 1, country_id: 39, code: "pa")
    ProviderCountry.create(provider_id: 1, country_id: 40, code: "pe")
    ProviderCountry.create(provider_id: 1, country_id: 41, code: "ph")
    ProviderCountry.create(provider_id: 1, country_id: 42, code: "pl")
    ProviderCountry.create(provider_id: 1, country_id: 43, code: "pt")
    ProviderCountry.create(provider_id: 1, country_id: 44, code: "qa")
    ProviderCountry.create(provider_id: 1, country_id: 45, code: "ro")
    ProviderCountry.create(provider_id: 1, country_id: 46, code: "ru")
    ProviderCountry.create(provider_id: 1, country_id: 47, code: "sa")
    ProviderCountry.create(provider_id: 1, country_id: 48, code: "sg")
    ProviderCountry.create(provider_id: 1, country_id: 49, code: "za")
    ProviderCountry.create(provider_id: 1, country_id: 50, code: "kr")
    ProviderCountry.create(provider_id: 1, country_id: 51, code: "es")
    ProviderCountry.create(provider_id: 1, country_id: 52, code: "se")
    ProviderCountry.create(provider_id: 1, country_id: 53, code: "ch")
    ProviderCountry.create(provider_id: 1, country_id: 54, code: "tw")
    ProviderCountry.create(provider_id: 1, country_id: 55, code: "th")
    ProviderCountry.create(provider_id: 1, country_id: 56, code: "tr")
    ProviderCountry.create(provider_id: 1, country_id: 57, code: "ua")
    ProviderCountry.create(provider_id: 1, country_id: 58, code: "ae")
    ProviderCountry.create(provider_id: 1, country_id: 59, code: "uk")
    ProviderCountry.create(provider_id: 1, country_id: 60, code: "us")
    ProviderCountry.create(provider_id: 1, country_id: 61, code: "uy")
    ProviderCountry.create(provider_id: 1, country_id: 62, code: "ve")
    ProviderCountry.create(provider_id: 1, country_id: 63, code: "vn")
  end
end
